FROM almalinux:9
LABEL author="srikanth" \
      course="Docker"   \
      duration="10hrs"  \
#by using this label we get our exact image by through label 
# [ ec2-user@ip-172-31-18-25 ~/dockerfiles/LABEL ]$ docker images --filter="label=course=Docker"
#                                                                                                                                              i Info →   U  In Use
# IMAGE      ID             DISK USAGE   CONTENT SIZE   EXTRA
# label:v1   03bc0226d960        279MB         71.7MB    U