FROM almalinux:9
#if i run with yahoo instead of google it will run becoz we can override it
#CMD ["ping", "google.com"]  
#But here it will not override it is static
#ENTRYPOINT [  "ping", "google.com" ]  

#by using both we get better results if you chnage google it will work insted yahoo
ENTRYPOINT ["ping"]
CMD ["yahoo.com"]
