FROM almalinux:9
#CMD ["ping", "google.com"] if i run with yahoo instead of google it will run
#ENTRYPOINT [  "ping", "google.com" ] But here it will not override it is static
ENTRYPOINT ["ping"]
CMD ["yahoo.com"]
