ARG version
FROM almalinux:${version:-9}
ARG course="docker" \
    duration="10hrs" 
ENV course=${course} \
    duration=${duration}
RUN echo "course is ${course} and time is in ${duration} and version is ${version}"