FROM almalinux:9
ADD https://github.com/daws-90s/notes/blob/main/session-45.txt /tmp/
#we can also extract all files in the /tmp directory its special feature in ADD instruction
ADD sample-1.tar /tmp/
CMD [ "sleep","100" ]