FROM almalinux:9
ENV author="Srikanth" \
    course="Docker"  \
    duration="10hrs" 
#by going inside container docker exec -it <container name> bash we see these values
#as we use almalinux se we have to give manuually CMD command to run container otherwise it will not 
CMD ["sleep", "120"] 