FROM almalinux:9
ENV author="Srikanth" \
    course="Docker"  \
    duration="10hrs" 
#by going inside container docker exec -it <container name> bash we see these values
#as we use almalinux se we have to give manuually CMD command to run container otherwise it will not 
CMD ["sleep", "1000"] 

## docker run -d -e  course="devops" env:v1 if i run these command
##i get devops instead of docker in env varibale if i check inside container terminal
